---
title: "DfE Dashboard Standards for Power BI reports and dashboards"
author: "Department for Education guidance"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
description: "DfE Dashboard Standards guide"
favicon: pictures/qa_logo.png
---

# Introduction

Power BI is Microsoft software that allows the user to create interactive dashboards/ reports/apps. It is designed to enable users to create self-service Business Intelligence (BI) tools, enabling their customers to make timely informed decisions based on their data.  

DfE analysts have been able to download and use Power BI since January 2018. From this date, analysts have been able to create internal tools and share them with colleagues within the department. From March 2019, analysts in ESFA Data Science Division have also been able to release dashboards to educational providers via a web portal called View Your Education Data (VYED). 

Below is a link to the gov.uk standards 

https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style

## Purpose

This document provides a high-level guide to aid in the design of consistent and high-quality Power BI dashboards.  

The overall aim of these guidelines is to help the analyst create logical, well-designed dashboards that are built correctly first time and easy for readers to understand and navigate, without any background reading. 

These guidelines are intended as a starting point for modellers when considering how to design dashboards, but it is for the modeller to determine how this is to be achieved. It is also hoped that this guide will start the conversation between modellers/teams to help improve standards.  

They are not designed to be a “colour by numbers” guide to dashboards, as each dashboard will have its own unique set of requirements and the modellers will have their own preferences and style.  

This document works alongside the Department’s Style Guide:  

[DfE style guide](https://educationgovuk.sharepoint.com/sites/how-do-i/SitePages/communications-style-guide.aspx)

To access the old version of the Dashboard Standards guidance, please click here:

[Dashboard Standards guidance](https://educationgovuk.sharepoint.com/:w:/r/sites/sarpi/g/_layouts/15/Doc.aspx?sourcedoc=%7B0EF92C8D-9F1D-40A7-8F18-8B3BE22CF303%7D&file=Dashboard%20Standards.docx&action=default&mobileredirect=true)

## Version control

* v0.1 Ricky Hindmarch, 22/10/2018. Initial draft.

* v0.2 Roman Kuzio, 22/11/2018. Continued draft.

* v0.3 Roman Kuzio, 28/11/2018. Reviewed comments from Ricky.

* v0.4 Roman Kuzio, 11/12/2018. Reviewed comments from Jenny.

* v0.5 Roman Kuzio, 12/12/2018. Incorporated further review comments from Jenny.

* v0.6 Roman Kuzio, 19/12/2018. Reviewed comments from Joe Grassby.

* v0.7 Jenny Cooley, 13/02/2019. Editing.

* v0.8 Aynsley Heath, 06/07/2020. Reviewed comments from team and updated documentation.

* v0.9 Ben Turner, 10/08/2020. Updated to include information on colour palette.

* v1.0 Jonathan Needham, 06/11/2020. Included an additional section on Quality Assurance.

* v1.1 Thomas Morley, 30/07/2021. Updated some links.

* v2.0 Thomas Morley, 17/09/2021. Created bookdown version.